services:
  # フロントエンド（静的サイト）
  - type: web
    name: study-english-idiom-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # APIサーバー（Node.js）
  - type: web
    name: study-english-idiom-api
    env: node
    buildCommand: npm install
    startCommand: npm run api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 